# Generated by Django 6.0.1 on 2026-03-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image_eventimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
