# Generated by Django 6.0.1 on 2026-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='email_from_name',
            field=models.CharField(blank=True, default='Athletics Events', max_length=100),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP server (e.g., smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='App password', max_length=255),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='Email address for sending', max_length=254),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='email_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
