# Generated by Django 6.0.1 on 2026-03-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_organizerprofile_email_from_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadminprofile',
            name='email_from_name',
            field=models.CharField(blank=True, default='Athletics Events Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='email_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
