# Generated by Django 6.0.1 on 2026-04-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_superadminprofile_email_from_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
