# Generated by Django 6.0.1 on 2026-04-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_registration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, default='confirmed', max_length=50, null=True),
        ),
    ]
